var namespace_suite_c_r_m_add_in_1_1_business_logic_1_1_tests =
[
    [ "LicenceValidationHelperTests", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_tests_1_1_licence_validation_helper_tests.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_tests_1_1_licence_validation_helper_tests" ],
    [ "SyncDirectionTests", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_tests_1_1_sync_direction_tests.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_tests_1_1_sync_direction_tests" ]
];