var namespace_suite_c_r_m_add_in_1_1_business_logic =
[
    [ "Tests", "namespace_suite_c_r_m_add_in_1_1_business_logic_1_1_tests.html", "namespace_suite_c_r_m_add_in_1_1_business_logic_1_1_tests" ],
    [ "AppointmentsSynchroniser", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_appointments_synchroniser.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_appointments_synchroniser" ],
    [ "AppointmentSyncState", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_appointment_sync_state.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_appointment_sync_state" ],
    [ "CallsSynchroniser", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_calls_synchroniser.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_calls_synchroniser" ],
    [ "CallSyncState", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_call_sync_state.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_call_sync_state" ],
    [ "ContactSynchroniser", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_contact_synchroniser.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_contact_synchroniser" ],
    [ "ContactSyncState", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_contact_sync_state.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_contact_sync_state" ],
    [ "CrmId", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_crm_id.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_crm_id" ],
    [ "CrmIdValidationPolicy", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_crm_id_validation_policy.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_crm_id_validation_policy" ],
    [ "CRMPermissionsCache", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_c_r_m_permissions_cache.html", null ],
    [ "EmailAccountsArchiveSettings", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_email_accounts_archive_settings.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_email_accounts_archive_settings" ],
    [ "EmailArchiving", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_email_archiving.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_email_archiving" ],
    [ "EmailCategoriesCollection", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_email_categories_collection.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_email_categories_collection" ],
    [ "ErrorHandler", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_error_handler.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_error_handler" ],
    [ "MeetingsSynchroniser", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_meetings_synchroniser.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_meetings_synchroniser" ],
    [ "MeetingSyncState", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_meeting_sync_state.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_meeting_sync_state" ],
    [ "RepeatingProcess", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_repeating_process.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_repeating_process" ],
    [ "SyncContext", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_sync_context.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_sync_context" ],
    [ "SyncDirection", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_sync_direction.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_sync_direction" ],
    [ "Synchroniser", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_synchroniser.html", null ],
    [ "SyncState", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_sync_state.html", null ],
    [ "SyncStateManager", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_sync_state_manager.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_sync_state_manager" ],
    [ "TaskSynchroniser", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_task_synchroniser.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_task_synchroniser" ],
    [ "TaskSyncState", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_task_sync_state.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_task_sync_state" ],
    [ "ThreadSafeList", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_thread_safe_list.html", "class_suite_c_r_m_add_in_1_1_business_logic_1_1_thread_safe_list" ],
    [ "WithRemovableSynchronisationProperties", "interface_suite_c_r_m_add_in_1_1_business_logic_1_1_with_removable_synchronisation_properties.html", "interface_suite_c_r_m_add_in_1_1_business_logic_1_1_with_removable_synchronisation_properties" ]
];